name: Build & Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
    - main

env:
  remote_host: "preview-mirror.mage-os.org"
  remote_dir: "/var/www/preview-mirror.mage-os.org/html/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to ${{ env.remote_host }}"
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: curl -L https://github.com/mage-os/php-dependency-list/raw/main/php-classes.phar -o /usr/local/bin/php-classes.phar && chmod +x /usr/local/bin/php-classes.phar
      name: "Install PHP source code dependency analyzer and make executable (used by nightly build script for base package)"

    - run: composer create-project composer/satis --stability=dev
    - run: npm ci
    - run: node src/make/mirror.js --outputDir=build/packages --gitRepoDir=generate-repo/repositories --repoUrl="${{ secrets.REPOSITORY_URL }}"
      name: "Generate the mirror packages"
    - run: node bin/set-satis-homepage-url.js --satisConfig=satis.json --repoUrl="${{ secrets.REPOSITORY_URL }}" > /tmp/satis.json
      name: "Configure satis repository URL so composer knows where to download packages from"
    - run: cat <<< $(jq '."output-dir" = "build" | .repositories[0].url = "build/packages"' /tmp/satis.json) > /tmp/satis.json
      name: "Tell satis where to find the generated packages"
    - run: satis/bin/satis build /tmp/satis.json build
    - run: node bin/set-satis-output-url-prefix.js --satisOutputDir=build --repoUrl="${{ secrets.REPOSITORY_URL }}"
      name: "Fix path to packages in the packages.json satis created"

    - uses: easingthemes/ssh-deploy@v2.2.11
      name: "Rsync over SSH"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ env.remote_host }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ env.remote_dir }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "build/*"
